### ISSUE TITLE
create_phylowgs_inputs.py ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by keyuan** [morrislab/phylowgs#2] opened 2015-05-21 21:33 UTC
Many thanks for putting the input parser code. I'm trying to use it to generate input files for the pilot 63 samples. I always get the following error:
```
python create_phylowgs_inputs.py -v sanger sample.vcf.gz
```

```
Traceback (most recent call last):
  File "create_phylowgs_inputs.py", line 685, in <module>
    main()
  File "create_phylowgs_inputs.py", line 659, in main
    variants_and_reads = variant_parser.list_variants()
  File "create_phylowgs_inputs.py", line 20, in list_variants
    ref_reads, total_reads = self._calc_read_counts(variant)
  File "create_phylowgs_inputs.py", line 111, in _calc_read_counts
    reference_nt, variant_nt = self._find_ref_and_variant_nt(variant)
  File "create_phylowgs_inputs.py", line 97, in _find_ref_and_variant_nt
    normal_genotype, tumor_genotype = genotype.split('/')
ValueError: need more than 1 value to unpack
```

Any idea of why this is happening? Many thanks!

**Comment by keyuan** [comment] 2015-05-22 10:47
It seems like the problem is with line 90 and it can be solved by replacing 
```
genotypes = [variant.INFO['TG'][0], variant.INFO['SG'][0]]
```
with
```
genotypes = [variant.INFO['TG'], variant.INFO['SG']]
```

**Comment by quaidmorris** [comment] 2015-05-22 19:24
Hi Ke,
Thanks for the potential bug fix. I'm not sure why you are getting this
problem -- Jeff uses the same code on the 63 samples but we'll look into it
as soon as we can.

Thanks!
Quaid

On Fri, May 22, 2015 at 6:47 AM, Ke Yuan <notifications@github.com> wrote:

> It seems like the problem is with line 90 and it can be solved by
> replacing
>
> genotypes = [variant.INFO['TG'][0], variant.INFO['SG'][0]]
>
> with
>
> genotypes = [variant.INFO['TG'], variant.INFO['SG']]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morrislab/phylowgs/issues/2#issuecomment-104616433>.
>



-- 
Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.med.utoronto.ca
cell:  (416) 220 5796

**Comment by jwintersinger** [comment] 2015-05-24 18:20
Hi Ke,

I'm not sure what the issue is -- as Quaid said, I've been using the parser on the Train 63 samples without any issue. To investigate, I inserted two lines at the top of `_find_ref_and_variant_nt`:

    def _find_ref_and_variant_nt(self, variant):
      from IPython import embed
      embed()
      ...

When running, I then find the following in IPython:

    In [1]: variant
    Out[1]: <vcf.model._Record at 0x7f2ce0892e50>

    In [2]: variant.INFO
    Out[2]: 
    {'DP': [40],
     'GP': ['6.4e-02'],
     'MP': ['9.4e-01'],
     'SG': ['CG/CG'],
     'SP': ['6.4e-02'],
     'TG': ['GG/CG'],
     'TP': ['9.3e-01']}

As you can see, each entry is a one-element array, necessitating the `[0]` index when accessing elements. Evidently, when you run it, you're not encountering the same behaviour.

May I ask your versions of Python and PyVCF? (You can find them by running `python --version` and `pip2 show PyVCF`, respectively.)  I'm using Python 2.7.7 and PyVCF 0.6.7.

Thanks!

**Comment by keyuan** [comment] 2015-05-24 21:03
Hi Jeff

This is what i get

```
In [1]: variant
Out[1]: <vcf.model._Record at 0x106d0d850>

In [2]: variant.INFO
Out[2]:
{'DP': 50,
 'GP': 1e-05,
 'MP': 1.0,
 'SG': 'CT/CT',
 'SP': 1e-05,
 'TG': 'CC/CT',
 'TP': 1.0}
```
My python version is 2.7.9
```
In [3]: vcf.VERSION
Out[3]: '0.6.7'
```
I use the pyvcf from https://github.com/jamescasbon/PyVCF.

**Comment by keyuan** [comment] 2015-05-24 21:04
I couldn't read the vcf with with the version from pip2

**Comment by jwintersinger** [comment] 2015-05-25 11:39
That's extremely odd, Ke! I figured the discrepancy between what you and I see arose because we were using different PyVCF versions -- you were using the development version from GitHub, while I was using the stable version installed by pip. To test this, I installed the latest version from GitHub, but I observed the same behaviour:

    In [1]: variant
    Out[1]: <vcf.model._Record at 0x7ff632fd1cd0>

    In [2]: vcf.__file__ # Yes, this is the dev version, not the stable one
    Out[2]: '/u/jwinters/work/exultant-pistachio/tmp/a876_d/PyVCF/vcf/__init__.pyc'

    In [3]: variant.INFO
    Out[3]: 
    {'DP': [40],
     'GP': ['6.4e-02'],
     'MP': ['9.4e-01'],
     'SG': ['CG/CG'],
     'SP': ['6.4e-02'],
     'TG': ['GG/CG'],
     'TP': ['9.3e-01']}

I could add a check to the parser to handle either the in-list case (what I see) or the no-list case (what you see), but I don't want to do so until I can reproduce the problem on my end. May I ask what is the full filename of the Train 63 VCF you're using?

Thank you for your help in figuring out where the issue lies, Ke!

**Comment by keyuan** [comment] 2015-05-28 16:18
Very strange indeed! This is happening to all of the Train 63 vcfs. But we can just test the first sample: 0c7af04b-e171-47c4-8be5-5db33f20148e.svcp_1-0-2.20141222.somatic.snv_mnv.vcf.gz

**Comment by jwintersinger** [comment] 2016-04-12 20:57
Hi Ke,
I'm going to close this and assume (hopefully) that the issue is resolved. Please let me know if it is not by opening another issue.

**Closed by jwintersinger** 2016-04-12 20:57 UTC

**Comment by keyuan** [comment] 2016-04-12 21:07
Hi Jeff,

The fix works well.

Best, ke
